// THIS FILE IS AUTOGENERATED, DO NOT EDIT
// Generated by mify

package main

import (
	"context"
	"example.com/namespace/workspace1/go-services/internal/service2/generated/app"
)

func main() {
	app := app.NewMifyServiceApp(context.Background())
	app.Run()
}
