generatorName: nodejs-express-server
templateDir: /repo/.mify/assets/openapi/server-template/js
enableMinimalUpdate: true
globalProperties: {}
additionalProperties:
  serverPort: 8080

releaseNote: Release note
httpUserAgent: User Agent

apiPackage: handlers
modelPackage: models

invokerPackage: unused
# packageName: api
apiNameSuffix: Api
modelNamePrefix: ""
modelNameSuffix: ""
artifactVersion: ARTIFACT_VERSION
library: ""

instantiationTypes: {}
typeMappings: {}
importMappings: {}
languageSpecificPrimitives: []
reservedWordMappings: {}
serverVariables: {}

verbose: false
skipOverwrite: false
removeOperationIdPrefix: false
skipOperationExample: false
logToStderr: false
validateSpec: true
enablePostProcessFile: false
strictSpecBehavior: true
generateAliasAsModel: false
templatingEngineName: mustache
# ignoreFileOverride: ""
