// THIS FILE IS AUTOGENERATED, DO NOT EDIT
// Generated by mify

package postgres

import "{{.Workspace.MifyGeneratedCommonPackage }}/configs"

type PostgresConfig struct {
	DatabaseUrl string `yaml:"database_url" envconfig:"DATABASE_URL" default:"postgres://user:passwd@localhost:5432/{{.Model.DatabaseName}}"`
}

func GetPostgresConfig(cfg *configs.MifyStaticConfig) *PostgresConfig {
	return cfg.MustGetPtr((*PostgresConfig)(nil)).(*PostgresConfig)
}
