// THIS FILE IS AUTOGENERATED, DO NOT EDIT
// Generated by mify

package postgres

import "{{.ConfigsImportPath}}"

type PostgresConfig struct {
	DatabaseUrl string `yaml:"database_url" envconfig:"DATABASE_URL" default:"127.0.0.1:8500"`
}

func GetPostgresConfig(cfg *configs.MifyStaticConfig) *PostgresConfig {
	return cfg.MustGetPtr((*PostgresConfig)(nil)).(*PostgresConfig)
}
