package render

import (
	"fmt"

	gencontext "github.com/mify-io/mify/pkg/generator/gen-context"
	"github.com/mify-io/mify/pkg/mifyconfig"
)

type GoServiceModel struct {
	Name string
}

type WorkspaceModel struct {
	Name       string
	Config     mifyconfig.WorkspaceConfig
	TplHeader  string

	PackageName string
}

func NewWorkspaceModel(context *gencontext.GenContext) *WorkspaceModel {
	return &WorkspaceModel{
		Name:       context.GetWorkspace().Name,
		Config:     context.GetWorkspace().Config,
		TplHeader:  "// THIS FILE IS AUTOGENERATED, DO NOT EDIT\n// Generated by mify",

		PackageName: getPackageName(context),
	}
}

func getPackageName(ctx *gencontext.GenContext) string {
	switch(ctx.MustGetMifySchema().Language) {
	case mifyconfig.ServiceLanguageGo:
		return getGoPackageName(ctx.GetWorkspace().Config)
	case mifyconfig.ServiceLanguageJs:
		// TODO update
		return ctx.MustGetMifySchema().ServiceName
	case mifyconfig.ServiceLanguagePython:
		// TODO update
		return ctx.MustGetMifySchema().ServiceName
	}
	panic(fmt.Sprintf("unknown language: %s", ctx.MustGetMifySchema().Language))
}

func getGoPackageName(config mifyconfig.WorkspaceConfig) string {
	return fmt.Sprintf("%s/%s/%s/go-services",
		config.GitHost,
		config.GitNamespace,
		config.GitRepository)
}
