// THIS FILE IS AUTOGENERATED, DO NOT EDIT
// Generated by mify

package main

import (
	"{{.Repository}}/go_services/internal/{{.ServiceName}}/generated/core"

	"go.uber.org/zap"
)

func main() {
	context, _ := core.NewMifyServiceContext("{{.ServiceName}}")

	context.Logger.Info("Starting...", zap.String("service_name", context.ServiceName))
}
