name: Go

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: latest

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Test
      run: make test

    - uses: goreleaser/goreleaser-action@v5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
