name: Go

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Test
      run: make test

    - uses: goreleaser/goreleaser-action@v5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
