name: Go

on:
  push:
    branches: [ '*' ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: latest

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Set version
      id: version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "::set-output name=release_version::$(echo ${GITHUB_REF:10})"

    - name: Build Release Packages
      if: startsWith(github.ref, 'refs/tags/')
      run: make build-packages

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        generate_release_notes: true
        name: Mify ${{ steps.version.outputs.release_version }}
        files: build/pkg/*

